"""Fitting puzzle piece images together.

Makes use of data generated by the 'analyze' script.
"""

import json

import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
import numpy as np


# Load the data.
with open('piece-data.json') as piece_data_file:
  piece_data = json.loads(piece_data_file.read())
piece_two = piece_data['sample-pieces/2.jpg']
piece_three = piece_data['sample-pieces/3.jpg']

# Setup each axis.
axis = plt.subplot('111')
axis.axis('off')
axis.set_aspect('equal')

# Get contours and shift them such that 2's last corner matches with 3's first
# corner.
piece_two_outline = np.array(piece_two['outline'])
piece_three_outline = np.array(piece_three['outline'])
x2, y2 = piece_two['corners'][3]
x3, y3 = piece_three['corners'][0]
dx = x2 - x3
dy = y2 - y3
shifted_piece_three_outline = np.array(
  [[x + dx, y + dy] for x, y in piece_three_outline])

# Show the outlines.
axis.plot(piece_two_outline[:, 0], piece_two_outline[:, 1], color='green')
axis.plot(shifted_piece_three_outline[:, 0], shifted_piece_three_outline[:, 1],
          color='blue')

# Show the figure.
plt.show()
figure = plt.gcf()
figure.savefig('fit.png', dpi=200)
